# Generated by Django 5.2.6 on 2025-09-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_menuitem_is_available_alter_menuitem_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
